<?php
	date_default_timezone_set("Asia/Hong_Kong");
	$host="localhost";
	$ser="root";
	$pass="Policy21!!!!";
	$db="smhs";
	$link = @mysql_connect($host, $ser, $pass) or die("Could not connect");
	mysql_select_db($db,$link) or die("Could not connect database");
	mysql_query("set names utf8");
	$ans = array();
	$sql = "";
	
	if (isset($_POST["data"])) {
		$data = explode("&", $_POST["data"]);
		//$_POST = explode("&", $_POST["data"]);
		foreach ($data as $key => $value) {
			list($k, $v) = explode("=", $value);
			$_POST[$k] = urldecode($v);//htmlspecialchars(urldecode($v), ENT_QUOTES);
			//echo $v."\n";
	}
	}
	
	foreach ($_POST as $key => $value) {
		$_POST[$key] = htmlspecialchars($value, ENT_QUOTES);
//		echo $_POST[$key]."\n";
	}

	if (!(isset($_POST["data"]))) {
		if (!(isset($_POST["addr"]))) {
			$sql = "insert into `smhsstat` (`sc`,`eno`,`tt`,`dd`,`st`,`et`,`stat`) values ('".@$_POST["sc"]."','".@$_POST["eno"]."','".@$_POST["ttt"]."','".@$_POST["ddd"]."','".@$_POST["st"]."','".date('h:i', time())."','".@$_POST["stat"]."')";
//			echo $sql;
			$result = mysql_query($sql,$link);
		}
	}

	
	$sql = "select * from smhsdb where sc = '".@$_POST["sc"]."'";
	$result = mysql_query($sql,$link);
	$num_rows = mysql_num_rows($result);
	if (@$_POST["sc"] != "") {
		if ($num_rows > 0) {
			$sql = "update smhsdb set ";
			$sql .= "`mm` = '".@$_POST["mm"]."', ";
			$sql .= "`dd` = '".@$_POST["dd"]."', ";
			$sql .= "`yy` = '".@$_POST["yy"]."', ";
			$sql .= "`tt` = '".@$_POST["tt"]."', ";
			$sql .= "`eno` = '".@$_POST["eno"]."', ";
			$sql .= "`qx1` = '".@$_POST["qx1"]."', ";
			$sql .= "`qx2` = '".@$_POST["qx2"]."', ";
			$sql .= "`qx3` = '".@$_POST["qx3"]."', ";
			$sql .= "`qb1` = '".@$_POST["qb1"]."', ";
			$sql .= "`qb2_1` = '".@$_POST["qb2_1"]."', ";
			$sql .= "`qb2_2` = '".@$_POST["qb2_2"]."', ";
			$sql .= "`qb2_3` = '".@$_POST["qb2_3"]."', ";
			$sql .= "`qb2_4` = '".@$_POST["qb2_4"]."', ";
			$sql .= "`qb2_5` = '".@$_POST["qb2_5"]."', ";
			$sql .= "`qb2_6` = '".@$_POST["qb2_6"]."', ";
			$sql .= "`qb2_7` = '".@$_POST["qb2_7"]."', ";
			$sql .= "`qb2_8` = '".@$_POST["qb2_8"]."', ";
			$sql .= "`qb2_8a` = '".@$_POST["qb2_8a"]."', ";
			$sql .= "`qb3` = '".@$_POST["qb3"]."', ";
			$sql .= "`qb3_1a` = '".@$_POST["qb3_1a"]."', ";
			$sql .= "`qb3_3a` = '".@$_POST["qb3_3a"]."', ";
			$sql .= "`qb3_4a` = '".@$_POST["qb3_4a"]."', ";
			$sql .= "`qb3a` = '".@$_POST["qb3a"]."', ";
			$sql .= "`qb3a_4a` = '".@$_POST["qb3a_4a"]."', ";
			$sql .= "`qb3b` = '".@$_POST["qb3b"]."', ";
			$sql .= "`qb4` = '".@$_POST["qb4"]."', ";
			$sql .= "`qb5` = '".@$_POST["qb5"]."', ";
			$sql .= "`qb5_99a` = '".@$_POST["qb5_99a"]."', ";
			$sql .= "`qb6` = '".@$_POST["qb6"]."', ";
			$sql .= "`qb6_5a` = '".@$_POST["qb6_5a"]."', ";
			$sql .= "`qb7` = '".@$_POST["qb7"]."', ";
			$sql .= "`qb7_2a` = '".@$_POST["qb7_2a"]."', ";
			$sql .= "`qb7a_1a` = '".@$_POST["qb7a_1a"]."', ";
			$sql .= "`qb7a_2a` = '".@$_POST["qb7a_2a"]."', ";
			$sql .= "`qb7a_3a` = '".@$_POST["qb7a_3a"]."', ";
			$sql .= "`qb7a_4a` = '".@$_POST["qb7a_4a"]."', ";
			$sql .= "`qb7a_5a` = '".@$_POST["qb7a_5a"]."', ";
			$sql .= "`qb7a_6b` = '".@$_POST["qb7a_6b"]."', ";
			$sql .= "`qb7a_6a` = '".@$_POST["qb7a_6a"]."', ";
			$sql .= "`qb8` = '".@$_POST["qb8"]."', ";
			$sql .= "`qb9` = '".@$_POST["qb9"]."', ";
			$sql .= "`qb10` = '".@$_POST["qb10"]."', ";
			$sql .= "`qb11` = '".@$_POST["qb11"]."', ";
			$sql .= "`qb12` = '".@$_POST["qb12"]."', ";
			$sql .= "`qb12_4a` = '".@$_POST["qb12_4a"]."', ";
			$sql .= "`qb12_7a` = '".@$_POST["qb12_7a"]."', ";
			$sql .= "`qb13` = '".@$_POST["qb13"]."', ";
			$sql .= "`qb13_9a` = '".@$_POST["qb13_9a"]."', ";
			$sql .= "`qb14` = '".@$_POST["qb14"]."', ";
			$sql .= "`qg1` = '".@$_POST["qg1"]."', ";
			$sql .= "`qg2` = '".@$_POST["qg2"]."', ";
			$sql .= "`qg2a` = '".@$_POST["qg2a"]."', ";
			$sql .= "`qg2b` = '".@$_POST["qg2b"]."', ";
			$sql .= "`qg3` = '".@$_POST["qg3"]."', ";
			$sql .= "`qg3a` = '".@$_POST["qg3a"]."', ";
			$sql .= "`qg4` = '".@$_POST["qg4"]."', ";
			$sql .= "`qg4a_1` = '".@$_POST["qg4a_1"]."', ";
			$sql .= "`qg4a_2` = '".@$_POST["qg4a_2"]."', ";
			$sql .= "`qg4a_3` = '".@$_POST["qg4a_3"]."', ";
			$sql .= "`qg4a_4` = '".@$_POST["qg4a_4"]."', ";
			$sql .= "`qg4a_5` = '".@$_POST["qg4a_5"]."', ";
			$sql .= "`qg4a_6` = '".@$_POST["qg4a_6"]."', ";
			$sql .= "`qg4a_7` = '".@$_POST["qg4a_7"]."', ";
			$sql .= "`qg4a_8` = '".@$_POST["qg4a_8"]."', ";
			$sql .= "`qg4a_9` = '".@$_POST["qg4a_9"]."', ";
			$sql .= "`qg4a_10` = '".@$_POST["qg4a_10"]."', ";
			$sql .= "`qg4a_11` = '".@$_POST["qg4a_11"]."', ";
			$sql .= "`qg4a_11a` = '".@$_POST["qg4a_11a"]."', ";
			$sql .= "`qhb1` = '".@$_POST["qhb1"]."', ";
			$sql .= "`qhb2` = '".@$_POST["qhb2"]."', ";
			$sql .= "`qhb3` = '".@$_POST["qhb3"]."', ";
			$sql .= "`qhb4` = '".@$_POST["qhb4"]."', ";
			$sql .= "`qhb13a_0` = '".@$_POST["qhb13a_0"]."', ";
			$sql .= "`qhb13a_1` = '".@$_POST["qhb13a_1"]."', ";
			$sql .= "`qhb13a_2` = '".@$_POST["qhb13a_2"]."', ";
			$sql .= "`qhb13a_3` = '".@$_POST["qhb13a_3"]."', ";
			$sql .= "`qhb13b_0` = '".@$_POST["qhb13b_0"]."', ";
			$sql .= "`qhb13b_1` = '".@$_POST["qhb13b_1"]."', ";
			$sql .= "`qhb13b_2` = '".@$_POST["qhb13b_2"]."', ";
			$sql .= "`qhb13b_3` = '".@$_POST["qhb13b_3"]."', ";
			$sql .= "`qhb13c_0` = '".@$_POST["qhb13c_0"]."', ";
			$sql .= "`qhb13c_1` = '".@$_POST["qhb13c_1"]."', ";
			$sql .= "`qhb13c_2` = '".@$_POST["qhb13c_2"]."', ";
			$sql .= "`qhb13c_3` = '".@$_POST["qhb13c_3"]."', ";
			$sql .= "`qhb13d_0` = '".@$_POST["qhb13d_0"]."', ";
			$sql .= "`qhb13d_1` = '".@$_POST["qhb13d_1"]."', ";
			$sql .= "`qhb13d_2` = '".@$_POST["qhb13d_2"]."', ";
			$sql .= "`qhb13d_3` = '".@$_POST["qhb13d_3"]."', ";
			$sql .= "`qhb13e_0` = '".@$_POST["qhb13e_0"]."', ";
			$sql .= "`qhb13e_1` = '".@$_POST["qhb13e_1"]."', ";
			$sql .= "`qhb13e_2` = '".@$_POST["qhb13e_2"]."', ";
			$sql .= "`qhb13e_3` = '".@$_POST["qhb13e_3"]."', ";
			$sql .= "`qhb13f_0` = '".@$_POST["qhb13f_0"]."', ";
			$sql .= "`qhb13f_1` = '".@$_POST["qhb13f_1"]."', ";
			$sql .= "`qhb13f_2` = '".@$_POST["qhb13f_2"]."', ";
			$sql .= "`qhb13f_3` = '".@$_POST["qhb13f_3"]."', ";
			$sql .= "`qhb13g_0` = '".@$_POST["qhb13g_0"]."', ";
			$sql .= "`qhb13g_1` = '".@$_POST["qhb13g_1"]."', ";
			$sql .= "`qhb13g_2` = '".@$_POST["qhb13g_2"]."', ";
			$sql .= "`qhb13g_3` = '".@$_POST["qhb13g_3"]."', ";
			$sql .= "`qhb13h_0` = '".@$_POST["qhb13h_0"]."', ";
			$sql .= "`qhb13h_1` = '".@$_POST["qhb13h_1"]."', ";
			$sql .= "`qhb13h_2` = '".@$_POST["qhb13h_2"]."', ";
			$sql .= "`qhb13h_3` = '".@$_POST["qhb13h_3"]."', ";
			$sql .= "`qhb13i_0` = '".@$_POST["qhb13i_0"]."', ";
			$sql .= "`qhb13i_1` = '".@$_POST["qhb13i_1"]."', ";
			$sql .= "`qhb13i_2` = '".@$_POST["qhb13i_2"]."', ";
			$sql .= "`qhb13i_3` = '".@$_POST["qhb13i_3"]."', ";
			$sql .= "`qhb13j_0` = '".@$_POST["qhb13j_0"]."', ";
			$sql .= "`qhb13j_1` = '".@$_POST["qhb13j_1"]."', ";
			$sql .= "`qhb13j_2` = '".@$_POST["qhb13j_2"]."', ";
			$sql .= "`qhb13j_3` = '".@$_POST["qhb13j_3"]."', ";
			$sql .= "`qhb13k_0` = '".@$_POST["qhb13k_0"]."', ";
			$sql .= "`qhb13k_1` = '".@$_POST["qhb13k_1"]."', ";
			$sql .= "`qhb13k_2` = '".@$_POST["qhb13k_2"]."', ";
			$sql .= "`qhb13k_3` = '".@$_POST["qhb13k_3"]."', ";
			$sql .= "`qmh4_1` = '".@$_POST["qmh4_1"]."', ";
			$sql .= "`qmh4_2` = '".@$_POST["qmh4_2"]."', ";
			$sql .= "`qmh4_3` = '".@$_POST["qmh4_3"]."', ";
			$sql .= "`qmh4_4` = '".@$_POST["qmh4_4"]."', ";
			$sql .= "`qmh4_5` = '".@$_POST["qmh4_5"]."', ";
			$sql .= "`qmh4_6` = '".@$_POST["qmh4_6"]."', ";
			$sql .= "`qmh4_7` = '".@$_POST["qmh4_7"]."', ";
			$sql .= "`qmh4_8` = '".@$_POST["qmh4_8"]."', ";
			$sql .= "`qmh4_9` = '".@$_POST["qmh4_9"]."', ";
			$sql .= "`qmh5a` = '".@$_POST["qmh5a"]."', ";
			$sql .= "`qmh5b` = '".@$_POST["qmh5b"]."', ";
			$sql .= "`qmh5b_5a` = '".@$_POST["qmh5b_5a"]."', ";
			$sql .= "`qmh5c_1` = '".@$_POST["qmh5c_1"]."', ";
			$sql .= "`qmh5c_2` = '".@$_POST["qmh5c_2"]."', ";
			$sql .= "`qmh5c_3` = '".@$_POST["qmh5c_3"]."', ";
			$sql .= "`qmh5c_4` = '".@$_POST["qmh5c_4"]."', ";
			$sql .= "`qmh5c_5` = '".@$_POST["qmh5c_5"]."', ";
			$sql .= "`qmh5c_5a` = '".@$_POST["qmh5c_5a"]."', ";
			$sql .= "`qs1` = '".@$_POST["qs1"]."', ";
			$sql .= "`qs1a` = '".@$_POST["qs1a"]."', ";
			$sql .= "`qs2` = '".@$_POST["qs2"]."', ";
			$sql .= "`qs3` = '".@$_POST["qs3"]."', ";
			$sql .= "`qs4` = '".@$_POST["qs4"]."', ";
			$sql .= "`qs5` = '".@$_POST["qs5"]."', ";
			$sql .= "`qs5a` = '".@$_POST["qs5a"]."', ";
			$sql .= "`qs6` = '".@$_POST["qs6"]."', ";
			$sql .= "`qs8` = '".@$_POST["qs8"]."', ";
			$sql .= "`qc1_1` = '".@$_POST["qc1_1"]."', ";
			$sql .= "`qc1_1_8a` = '".@$_POST["qc1_1_8a"]."', ";
			$sql .= "`qc1_2` = '".@$_POST["qc1_2"]."', ";
			$sql .= "`qc1_2_8a` = '".@$_POST["qc1_2_8a"]."', ";
			$sql .= "`qc2` = '".@$_POST["qc2"]."', ";
			$sql .= "`qc3` = '".@$_POST["qc3"]."', ";
			$sql .= "`qc4` = '".@$_POST["qc4"]."', ";
			$sql .= "`qc5` = '".@$_POST["qc5"]."', ";
			$sql .= "`qc6` = '".@$_POST["qc6"]."', ";
			$sql .= "`qc7` = '".@$_POST["qc7"]."', ";
			$sql .= "`qce1` = '".@$_POST["qce1"]."', ";
			$sql .= "`qce2` = '".@$_POST["qce2"]."', ";
			$sql .= "`qce3` = '".@$_POST["qce3"]."', ";
			$sql .= "`qce4` = '".@$_POST["qce4"]."', ";
			$sql .= "`qce5` = '".@$_POST["qce5"]."', ";
			$sql .= "`qce6` = '".@$_POST["qce6"]."', ";
			$sql .= "`qce7` = '".@$_POST["qce7"]."', ";
			$sql .= "`qce8` = '".@$_POST["qce8"]."', ";
			$sql .= "`qce9` = '".@$_POST["qce9"]."', ";
			$sql .= "`qce10` = '".@$_POST["qce10"]."', ";
			$sql .= "`qce11` = '".@$_POST["qce11"]."', ";
			$sql .= "`qce12` = '".@$_POST["qce12"]."', ";
			$sql .= "`qce13` = '".@$_POST["qce13"]."', ";
			$sql .= "`qce14` = '".@$_POST["qce14"]."', ";
			$sql .= "`qfs1` = '".@$_POST["qfs1"]."', ";
			$sql .= "`qfs2` = '".@$_POST["qfs2"]."', ";
			$sql .= "`qfs3` = '".@$_POST["qfs3"]."', ";
			$sql .= "`qfs4` = '".@$_POST["qfs4"]."', ";
			$sql .= "`qst2` = '".@$_POST["qst2"]."', ";
			$sql .= "`qst2_4a` = '".@$_POST["qst2_4a"]."', ";
			$sql .= "`qst3` = '".@$_POST["qst3"]."', ";
			$sql .= "`qst4` = '".@$_POST["qst4"]."', ";
			$sql .= "`qst5` = '".@$_POST["qst5"]."', ";
			$sql .= "`qst6` = '".@$_POST["qst6"]."', ";
			$sql .= "`qst6_7a` = '".@$_POST["qst6_7a"]."', ";
			$sql .= "`qst7` = '".@$_POST["qst7"]."', ";
			$sql .= "`qst7_7a` = '".@$_POST["qst7_7a"]."', ";
			$sql .= "`qst8` = '".@$_POST["qst8"]."', ";
			$sql .= "`qst8_5a` = '".@$_POST["qst8_5a"]."', ";
			$sql .= "`qst9` = '".@$_POST["qst9"]."', ";
			$sql .= "`qst10` = '".@$_POST["qst10"]."', ";
			$sql .= "`qsa1` = '".@$_POST["qsa1"]."', ";
			$sql .= "`qsa2` = '".@$_POST["qsa2"]."', ";
			$sql .= "`qsa3` = '".@$_POST["qsa3"]."', ";
			$sql .= "`qsa4` = '".@$_POST["qsa4"]."', ";
			$sql .= "`qsa4_5a` = '".@$_POST["qsa4_5a"]."', ";
			$sql .= "`qsa5` = '".@$_POST["qsa5"]."', ";
			$sql .= "`qd0` = '".@$_POST["qd0"]."', ";
			$sql .= "`qd1` = '".@$_POST["qd1"]."', ";
			$sql .= "`qd1_6a` = '".@$_POST["qd1_6a"]."', ";
			$sql .= "`qd2` = '".@$_POST["qd2"]."', ";
			$sql .= "`qd3` = '".@$_POST["qd3"]."', ";
			$sql .= "`qd3a` = '".@$_POST["qd3a"]."', ";
			$sql .= "`qd3aa` = '".@$_POST["qd3aa"]."', ";
			$sql .= "`qd3b` = '".@$_POST["qd3b"]."', ";
			$sql .= "`qd3ba` = '".@$_POST["qd3ba"]."', ";
			$sql .= "`qd3c` = '".@$_POST["qd3c"]."', ";
			$sql .= "`qd3ca` = '".@$_POST["qd3ca"]."', ";
			$sql .= "`qd3d` = '".@$_POST["qd3d"]."', ";
			$sql .= "`qd3da` = '".@$_POST["qd3da"]."', ";
			$sql .= "`qd3e` = '".@$_POST["qd3e"]."', ";
			$sql .= "`qd3ea` = '".@$_POST["qd3ea"]."', ";
			$sql .= "`qd3f` = '".@$_POST["qd3f"]."', ";
			$sql .= "`qd3fa` = '".@$_POST["qd3fa"]."', ";
			$sql .= "`qd3g` = '".@$_POST["qd3g"]."', ";
			$sql .= "`qd3ga` = '".@$_POST["qd3ga"]."', ";
			$sql .= "`qd3h` = '".@$_POST["qd3h"]."', ";
			$sql .= "`qd3ha` = '".@$_POST["qd3ha"]."', ";
			$sql .= "`qd3i` = '".@$_POST["qd3i"]."', ";
			$sql .= "`qd3ia` = '".@$_POST["qd3ia"]."', ";
			$sql .= "`qd3j` = '".@$_POST["qd3j"]."', ";
			$sql .= "`qd3ja` = '".@$_POST["qd3ja"]."', ";
			$sql .= "`qd3k` = '".@$_POST["qd3k"]."', ";
			$sql .= "`qd3ka` = '".@$_POST["qd3ka"]."', ";
			$sql .= "`qd3l` = '".@$_POST["qd3l"]."', ";
			$sql .= "`qd3la` = '".@$_POST["qd3la"]."', ";
			$sql .= "`qd3_12a` = '".@$_POST["qd3_12a"]."', ";
			$sql .= "`qd3m` = '".@$_POST["qd3m"]."', ";
			$sql .= "`qd4_1` = '".@$_POST["qd4_1"]."', ";
			$sql .= "`qd4_2` = '".@$_POST["qd4_2"]."', ";
			$sql .= "`qd4_3` = '".@$_POST["qd4_3"]."', ";
			$sql .= "`qd4_4` = '".@$_POST["qd4_4"]."', ";
			$sql .= "`qd4_5` = '".@$_POST["qd4_5"]."', ";
			$sql .= "`qd4_6` = '".@$_POST["qd4_6"]."', ";
			$sql .= "`qd4_6a` = '".@$_POST["qd4_6a"]."', ";
			$sql .= "`qd5` = '".@$_POST["qd5"]."', ";
			$sql .= "`qd6` = '".@$_POST["qd6"]."', ";
			$sql .= "`qd6_6a` = '".@$_POST["qd6_6a"]."', ";
			$sql .= "`qd7` = '".@$_POST["qd7"]."', ";
			$sql .= "`qd7_5a` = '".@$_POST["qd7_5a"]."', ";
			$sql .= "`qd8_1` = '".@$_POST["qd8_1"]."', ";
			$sql .= "`qd8_2` = '".@$_POST["qd8_2"]."', ";
			$sql .= "`qd8_3` = '".@$_POST["qd8_3"]."', ";
			$sql .= "`qd8_4` = '".@$_POST["qd8_4"]."', ";
			$sql .= "`qd8_5` = '".@$_POST["qd8_5"]."', ";
			$sql .= "`qd8_6` = '".@$_POST["qd8_6"]."', ";
			$sql .= "`qd9_1` = '".@$_POST["qd9_1"]."', ";
			$sql .= "`qd9_2` = '".@$_POST["qd9_2"]."', ";
			$sql .= "`qd9_3` = '".@$_POST["qd9_3"]."', ";
			$sql .= "`qd9_4` = '".@$_POST["qd9_4"]."', ";
			$sql .= "`qd9_5` = '".@$_POST["qd9_5"]."', ";
			$sql .= "`qd9_6` = '".@$_POST["qd9_6"]."', ";
			$sql .= "`qd10_1` = '".@$_POST["qd10_1"]."', ";
			$sql .= "`qd10_2` = '".@$_POST["qd10_2"]."', ";
			$sql .= "`qd10_3` = '".@$_POST["qd10_3"]."', ";
			$sql .= "`qd10_4` = '".@$_POST["qd10_4"]."', ";
			$sql .= "`qd10_5` = '".@$_POST["qd10_5"]."', ";
			$sql .= "`qd10_6` = '".@$_POST["qd10_6"]."', ";
			$sql .= "`qd11_1` = '".@$_POST["qd11_1"]."', ";
			$sql .= "`qd11_2` = '".@$_POST["qd11_2"]."', ";
			$sql .= "`qd11_3` = '".@$_POST["qd11_3"]."', ";
			$sql .= "`qd11_4` = '".@$_POST["qd11_4"]."', ";
			$sql .= "`qd11_5` = '".@$_POST["qd11_5"]."', ";
			$sql .= "`qd11_6` = '".@$_POST["qd11_6"]."', ";
			$sql .= "`qd12_1` = '".@$_POST["qd12_1"]."', ";
			$sql .= "`qd12_2` = '".@$_POST["qd12_2"]."', ";
			$sql .= "`qd12_3` = '".@$_POST["qd12_3"]."', ";
			$sql .= "`qd12_4` = '".@$_POST["qd12_4"]."', ";
			$sql .= "`qd12_5` = '".@$_POST["qd12_5"]."', ";
			$sql .= "`qd12_6` = '".@$_POST["qd12_6"]."', ";
			$sql .= "`qse1_1` = '".@$_POST["qse1_1"]."', ";
			$sql .= "`qse1_2` = '".@$_POST["qse1_2"]."', ";
			$sql .= "`qse1_3` = '".@$_POST["qse1_3"]."', ";
			$sql .= "`qse1_4` = '".@$_POST["qse1_4"]."', ";
			$sql .= "`qse1_5` = '".@$_POST["qse1_5"]."', ";
			$sql .= "`qse1_6` = '".@$_POST["qse1_6"]."', ";
			$sql .= "`qse2_1` = '".@$_POST["qse2_1"]."', ";
			$sql .= "`qse2_2` = '".@$_POST["qse2_2"]."', ";
			$sql .= "`qse2_3` = '".@$_POST["qse2_3"]."', ";
			$sql .= "`qse2_4` = '".@$_POST["qse2_4"]."', ";
			$sql .= "`qse2_5` = '".@$_POST["qse2_5"]."', ";
			$sql .= "`qse2_6` = '".@$_POST["qse2_6"]."', ";
			$sql .= "`qse3_1` = '".@$_POST["qse3_1"]."', ";
			$sql .= "`qse3_2` = '".@$_POST["qse3_2"]."', ";
			$sql .= "`qse3_3` = '".@$_POST["qse3_3"]."', ";
			$sql .= "`qse3_4` = '".@$_POST["qse3_4"]."', ";
			$sql .= "`qse3_5` = '".@$_POST["qse3_5"]."', ";
			$sql .= "`qse3_6` = '".@$_POST["qse3_6"]."', ";
			$sql .= "`qse4_1` = '".@$_POST["qse4_1"]."', ";
			$sql .= "`qse4_2` = '".@$_POST["qse4_2"]."', ";
			$sql .= "`qse4_3` = '".@$_POST["qse4_3"]."', ";
			$sql .= "`qse4_4` = '".@$_POST["qse4_4"]."', ";
			$sql .= "`qse4_5` = '".@$_POST["qse4_5"]."', ";
			$sql .= "`qse4_6` = '".@$_POST["qse4_6"]."', ";
			$sql .= "`qse5_1` = '".@$_POST["qse5_1"]."', ";
			$sql .= "`qse5_2` = '".@$_POST["qse5_2"]."', ";
			$sql .= "`qse5_3` = '".@$_POST["qse5_3"]."', ";
			$sql .= "`qse5_4` = '".@$_POST["qse5_4"]."', ";
			$sql .= "`qse5_5` = '".@$_POST["qse5_5"]."', ";
			$sql .= "`qse5_6` = '".@$_POST["qse5_6"]."', ";
			$sql .= "`qse6_1` = '".@$_POST["qse6_1"]."', ";
			$sql .= "`qse6_2` = '".@$_POST["qse6_2"]."', ";
			$sql .= "`qse6_3` = '".@$_POST["qse6_3"]."', ";
			$sql .= "`qse6_4` = '".@$_POST["qse6_4"]."', ";
			$sql .= "`qse6_5` = '".@$_POST["qse6_5"]."', ";
			$sql .= "`qse6_6` = '".@$_POST["qse6_6"]."', ";
			$sql .= "`qse7_1` = '".@$_POST["qse7_1"]."', ";
			$sql .= "`qse7_2` = '".@$_POST["qse7_2"]."', ";
			$sql .= "`qse7_3` = '".@$_POST["qse7_3"]."', ";
			$sql .= "`qse7_4` = '".@$_POST["qse7_4"]."', ";
			$sql .= "`qse7_5` = '".@$_POST["qse7_5"]."', ";
			$sql .= "`qse7_6` = '".@$_POST["qse7_6"]."', ";
			$sql .= "`qse8_1` = '".@$_POST["qse8_1"]."', ";
			$sql .= "`qse8_2` = '".@$_POST["qse8_2"]."', ";
			$sql .= "`qse8_3` = '".@$_POST["qse8_3"]."', ";
			$sql .= "`qse8_4` = '".@$_POST["qse8_4"]."', ";
			$sql .= "`qse8_5` = '".@$_POST["qse8_5"]."', ";
			$sql .= "`qse8_6` = '".@$_POST["qse8_6"]."', ";
			$sql .= "`qse9_1` = '".@$_POST["qse9_1"]."', ";
			$sql .= "`qse9_2` = '".@$_POST["qse9_2"]."', ";
			$sql .= "`qse9_3` = '".@$_POST["qse9_3"]."', ";
			$sql .= "`qse9_4` = '".@$_POST["qse9_4"]."', ";
			$sql .= "`qse9_5` = '".@$_POST["qse9_5"]."', ";
			$sql .= "`qse9_6` = '".@$_POST["qse9_6"]."', ";
			$sql .= "`qse10_1` = '".@$_POST["qse10_1"]."', ";
			$sql .= "`qse10_2` = '".@$_POST["qse10_2"]."', ";
			$sql .= "`qse10_3` = '".@$_POST["qse10_3"]."', ";
			$sql .= "`qse10_4` = '".@$_POST["qse10_4"]."', ";
			$sql .= "`qse10_5` = '".@$_POST["qse10_5"]."', ";
			$sql .= "`qse10_6` = '".@$_POST["qse10_6"]."', ";
			$sql .= "`qse11_1` = '".@$_POST["qse11_1"]."', ";
			$sql .= "`qse11_2` = '".@$_POST["qse11_2"]."', ";
			$sql .= "`qse11_3` = '".@$_POST["qse11_3"]."', ";
			$sql .= "`qse11_4` = '".@$_POST["qse11_4"]."', ";
			$sql .= "`qse11_5` = '".@$_POST["qse11_5"]."', ";
			$sql .= "`qse11_6` = '".@$_POST["qse11_6"]."', ";
			$sql .= "`qse12_1` = '".@$_POST["qse12_1"]."', ";
			$sql .= "`qse12_2` = '".@$_POST["qse12_2"]."', ";
			$sql .= "`qse12_3` = '".@$_POST["qse12_3"]."', ";
			$sql .= "`qse12_4` = '".@$_POST["qse12_4"]."', ";
			$sql .= "`qse12_5` = '".@$_POST["qse12_5"]."', ";
			$sql .= "`qse12_6` = '".@$_POST["qse12_6"]."', ";
			$sql .= "`qse13_1` = '".@$_POST["qse13_1"]."', ";
			$sql .= "`qse13_2` = '".@$_POST["qse13_2"]."', ";
			$sql .= "`qse13_3` = '".@$_POST["qse13_3"]."', ";
			$sql .= "`qse13_4` = '".@$_POST["qse13_4"]."', ";
			$sql .= "`qse13_5` = '".@$_POST["qse13_5"]."', ";
			$sql .= "`qse13_6` = '".@$_POST["qse13_6"]."', ";
			$sql .= "`qse14_1` = '".@$_POST["qse14_1"]."', ";
			$sql .= "`qse14_2` = '".@$_POST["qse14_2"]."', ";
			$sql .= "`qse14_3` = '".@$_POST["qse14_3"]."', ";
			$sql .= "`qse14_4` = '".@$_POST["qse14_4"]."', ";
			$sql .= "`qse14_5` = '".@$_POST["qse14_5"]."', ";
			$sql .= "`qse14_6` = '".@$_POST["qse14_6"]."', ";
			$sql .= "`qse15_1` = '".@$_POST["qse15_1"]."', ";
			$sql .= "`qse15_2` = '".@$_POST["qse15_2"]."', ";
			$sql .= "`qse15_3` = '".@$_POST["qse15_3"]."', ";
			$sql .= "`qse15_4` = '".@$_POST["qse15_4"]."', ";
			$sql .= "`qse15_5` = '".@$_POST["qse15_5"]."', ";
			$sql .= "`qse15_6` = '".@$_POST["qse15_6"]."', ";
			$sql .= "`qse16_1` = '".@$_POST["qse16_1"]."', ";
			$sql .= "`qse16_2` = '".@$_POST["qse16_2"]."', ";
			$sql .= "`qse16_3` = '".@$_POST["qse16_3"]."', ";
			$sql .= "`qse16_4` = '".@$_POST["qse16_4"]."', ";
			$sql .= "`qse16_5` = '".@$_POST["qse16_5"]."', ";
			$sql .= "`qse16_6` = '".@$_POST["qse16_6"]."', ";
			$sql .= "`qse17_1` = '".@$_POST["qse17_1"]."', ";
			$sql .= "`qse17_2` = '".@$_POST["qse17_2"]."', ";
			$sql .= "`qse17_3` = '".@$_POST["qse17_3"]."', ";
			$sql .= "`qse17_4` = '".@$_POST["qse17_4"]."', ";
			$sql .= "`qse17_5` = '".@$_POST["qse17_5"]."', ";
			$sql .= "`qse17_6` = '".@$_POST["qse17_6"]."', ";
			$sql .= "`qse18a` = '".@$_POST["qse18a"]."', ";
			$sql .= "`qse18b` = '".@$_POST["qse18b"]."', ";
			$sql .= "`qse18c` = '".@$_POST["qse18c"]."', ";
			$sql .= "`qa1_1a` = '".@$_POST["qa1_1a"]."', ";
			$sql .= "`qa2_1a` = '".@$_POST["qa2_1a"]."', ";
			$sql .= "`qa3_1a` = '".@$_POST["qa3_1a"]."', ";
			$sql .= "`qa4_1a` = '".@$_POST["qa4_1a"]."', ";
			$sql .= "`qpoc1` = '".@$_POST["qpoc1"]."', ";
			$sql .= "`qpoc2` = '".@$_POST["qpoc2"]."', ";
			$sql .= "`qpoc2_1a` = '".@$_POST["qpoc2_1a"]."', ";
			$sql .= "`qa5` = '".@$_POST["qa5"]."', ";
			$sql .= "`qa6a` = '".@$_POST["qa6a"]."', ";
			$sql .= "`qa6b` = '".@$_POST["qa6b"]."', ";
			$sql .= "`qa6c` = '".@$_POST["qa6c"]."', ";
			$sql .= "`qa6d` = '".@$_POST["qa6d"]."', ";
			$sql .= "`qa6da` = '".@$_POST["qa6da"]."', ";
			$sql .= "`qa7` = '".@$_POST["qa7"]."', ";
			$sql .= "`qa8a` = '".@$_POST["qa8a"]."', ";
			$sql .= "`qa8b` = '".@$_POST["qa8b"]."' ";
			$sql .= "where `sc` = '".@$_POST["sc"]."'";
		} else {
			$sql = "insert into smhsdb (";
			$sql .= "`sc`, ";
			$sql .= "`mm`, ";
			$sql .= "`dd`, ";
			$sql .= "`yy`, ";
			$sql .= "`tt`, ";
			$sql .= "`eno`, ";
			$sql .= "`qx1`, ";
			$sql .= "`qx2`, ";
			$sql .= "`qx3`, ";
			$sql .= "`qb1`, ";
			$sql .= "`qb2_1`, ";
			$sql .= "`qb2_2`, ";
			$sql .= "`qb2_3`, ";
			$sql .= "`qb2_4`, ";
			$sql .= "`qb2_5`, ";
			$sql .= "`qb2_6`, ";
			$sql .= "`qb2_7`, ";
			$sql .= "`qb2_8`, ";
			$sql .= "`qb2_8a`, ";
			$sql .= "`qb3`, ";
			$sql .= "`qb3_1a`, ";
			$sql .= "`qb3_3a`, ";
			$sql .= "`qb3_4a`, ";
			$sql .= "`qb3a`, ";
			$sql .= "`qb3a_4a`, ";
			$sql .= "`qb3b`, ";
			$sql .= "`qb4`, ";
			$sql .= "`qb5`, ";
			$sql .= "`qb5_99a`, ";
			$sql .= "`qb6`, ";
			$sql .= "`qb6_5a`, ";
			$sql .= "`qb7`, ";
			$sql .= "`qb7_2a`, ";
			$sql .= "`qb7a_1a`, ";
			$sql .= "`qb7a_2a`, ";
			$sql .= "`qb7a_3a`, ";
			$sql .= "`qb7a_4a`, ";
			$sql .= "`qb7a_5a`, ";
			$sql .= "`qb7a_6b`, ";
			$sql .= "`qb7a_6a`, ";
			$sql .= "`qb8`, ";
			$sql .= "`qb9`, ";
			$sql .= "`qb10`, ";
			$sql .= "`qb11`, ";
			$sql .= "`qb12`, ";
			$sql .= "`qb12_4a`, ";
			$sql .= "`qb12_7a`, ";
			$sql .= "`qb13`, ";
			$sql .= "`qb13_9a`, ";
			$sql .= "`qb14`, ";
			$sql .= "`qg1`, ";
			$sql .= "`qg2`, ";
			$sql .= "`qg2a`, ";
			$sql .= "`qg2b`, ";
			$sql .= "`qg3`, ";
			$sql .= "`qg3a`, ";
			$sql .= "`qg4`, ";
			$sql .= "`qg4a_1`, ";
			$sql .= "`qg4a_2`, ";
			$sql .= "`qg4a_3`, ";
			$sql .= "`qg4a_4`, ";
			$sql .= "`qg4a_5`, ";
			$sql .= "`qg4a_6`, ";
			$sql .= "`qg4a_7`, ";
			$sql .= "`qg4a_8`, ";
			$sql .= "`qg4a_9`, ";
			$sql .= "`qg4a_10`, ";
			$sql .= "`qg4a_11`, ";
			$sql .= "`qg4a_11a`, ";
			$sql .= "`qhb1`, ";
			$sql .= "`qhb2`, ";
			$sql .= "`qhb3`, ";
			$sql .= "`qhb4`, ";
			$sql .= "`qhb13a_0`, ";
			$sql .= "`qhb13a_1`, ";
			$sql .= "`qhb13a_2`, ";
			$sql .= "`qhb13a_3`, ";
			$sql .= "`qhb13b_0`, ";
			$sql .= "`qhb13b_1`, ";
			$sql .= "`qhb13b_2`, ";
			$sql .= "`qhb13b_3`, ";
			$sql .= "`qhb13c_0`, ";
			$sql .= "`qhb13c_1`, ";
			$sql .= "`qhb13c_2`, ";
			$sql .= "`qhb13c_3`, ";
			$sql .= "`qhb13d_0`, ";
			$sql .= "`qhb13d_1`, ";
			$sql .= "`qhb13d_2`, ";
			$sql .= "`qhb13d_3`, ";
			$sql .= "`qhb13e_0`, ";
			$sql .= "`qhb13e_1`, ";
			$sql .= "`qhb13e_2`, ";
			$sql .= "`qhb13e_3`, ";
			$sql .= "`qhb13f_0`, ";
			$sql .= "`qhb13f_1`, ";
			$sql .= "`qhb13f_2`, ";
			$sql .= "`qhb13f_3`, ";
			$sql .= "`qhb13g_0`, ";
			$sql .= "`qhb13g_1`, ";
			$sql .= "`qhb13g_2`, ";
			$sql .= "`qhb13g_3`, ";
			$sql .= "`qhb13h_0`, ";
			$sql .= "`qhb13h_1`, ";
			$sql .= "`qhb13h_2`, ";
			$sql .= "`qhb13h_3`, ";
			$sql .= "`qhb13i_0`, ";
			$sql .= "`qhb13i_1`, ";
			$sql .= "`qhb13i_2`, ";
			$sql .= "`qhb13i_3`, ";
			$sql .= "`qhb13j_0`, ";
			$sql .= "`qhb13j_1`, ";
			$sql .= "`qhb13j_2`, ";
			$sql .= "`qhb13j_3`, ";
			$sql .= "`qhb13k_0`, ";
			$sql .= "`qhb13k_1`, ";
			$sql .= "`qhb13k_2`, ";
			$sql .= "`qhb13k_3`, ";
			$sql .= "`qmh4_1`, ";
			$sql .= "`qmh4_2`, ";
			$sql .= "`qmh4_3`, ";
			$sql .= "`qmh4_4`, ";
			$sql .= "`qmh4_5`, ";
			$sql .= "`qmh4_6`, ";
			$sql .= "`qmh4_7`, ";
			$sql .= "`qmh4_8`, ";
			$sql .= "`qmh4_9`, ";
			$sql .= "`qmh5a`, ";
			$sql .= "`qmh5b`, ";
			$sql .= "`qmh5b_5a`, ";
			$sql .= "`qmh5c_1`, ";
			$sql .= "`qmh5c_2`, ";
			$sql .= "`qmh5c_3`, ";
			$sql .= "`qmh5c_4`, ";
			$sql .= "`qmh5c_5`, ";
			$sql .= "`qmh5c_5a`, ";
			$sql .= "`qs1`, ";
			$sql .= "`qs1a`, ";
			$sql .= "`qs2`, ";
			$sql .= "`qs3`, ";
			$sql .= "`qs4`, ";
			$sql .= "`qs5`, ";
			$sql .= "`qs5a`, ";
			$sql .= "`qs6`, ";
			$sql .= "`qs8`, ";
			$sql .= "`qc1_1`, ";
			$sql .= "`qc1_1_8a`, ";
			$sql .= "`qc1_2`, ";
			$sql .= "`qc1_2_8a`, ";
			$sql .= "`qc2`, ";
			$sql .= "`qc3`, ";
			$sql .= "`qc4`, ";
			$sql .= "`qc5`, ";
			$sql .= "`qc6`, ";
			$sql .= "`qc7`, ";
			$sql .= "`qce1`, ";
			$sql .= "`qce2`, ";
			$sql .= "`qce3`, ";
			$sql .= "`qce4`, ";
			$sql .= "`qce5`, ";
			$sql .= "`qce6`, ";
			$sql .= "`qce7`, ";
			$sql .= "`qce8`, ";
			$sql .= "`qce9`, ";
			$sql .= "`qce10`, ";
			$sql .= "`qce11`, ";
			$sql .= "`qce12`, ";
			$sql .= "`qce13`, ";
			$sql .= "`qce14`, ";
			$sql .= "`qfs1`, ";
			$sql .= "`qfs2`, ";
			$sql .= "`qfs3`, ";
			$sql .= "`qfs4`, ";
			$sql .= "`qst2`, ";
			$sql .= "`qst2_4a`, ";
			$sql .= "`qst3`, ";
			$sql .= "`qst4`, ";
			$sql .= "`qst5`, ";
			$sql .= "`qst6`, ";
			$sql .= "`qst6_7a`, ";
			$sql .= "`qst7`, ";
			$sql .= "`qst7_7a`, ";
			$sql .= "`qst8`, ";
			$sql .= "`qst8_5a`, ";
			$sql .= "`qst9`, ";
			$sql .= "`qst10`, ";
			$sql .= "`qsa1`, ";
			$sql .= "`qsa2`, ";
			$sql .= "`qsa3`, ";
			$sql .= "`qsa4`, ";
			$sql .= "`qsa4_5a`, ";
			$sql .= "`qsa5`, ";
			$sql .= "`qd0`, ";
			$sql .= "`qd1`, ";
			$sql .= "`qd1_6a`, ";
			$sql .= "`qd2`, ";
			$sql .= "`qd3`, ";
			$sql .= "`qd3a`, ";
			$sql .= "`qd3aa`, ";
			$sql .= "`qd3b`, ";
			$sql .= "`qd3ba`, ";
			$sql .= "`qd3c`, ";
			$sql .= "`qd3ca`, ";
			$sql .= "`qd3d`, ";
			$sql .= "`qd3da`, ";
			$sql .= "`qd3e`, ";
			$sql .= "`qd3ea`, ";
			$sql .= "`qd3f`, ";
			$sql .= "`qd3fa`, ";
			$sql .= "`qd3g`, ";
			$sql .= "`qd3ga`, ";
			$sql .= "`qd3h`, ";
			$sql .= "`qd3ha`, ";
			$sql .= "`qd3i`, ";
			$sql .= "`qd3ia`, ";
			$sql .= "`qd3j`, ";
			$sql .= "`qd3ja`, ";
			$sql .= "`qd3k`, ";
			$sql .= "`qd3ka`, ";
			$sql .= "`qd3l`, ";
			$sql .= "`qd3la`, ";
			$sql .= "`qd3_12a`, ";
			$sql .= "`qd3m`, ";
			$sql .= "`qd4_1`, ";
			$sql .= "`qd4_2`, ";
			$sql .= "`qd4_3`, ";
			$sql .= "`qd4_4`, ";
			$sql .= "`qd4_5`, ";
			$sql .= "`qd4_6`, ";
			$sql .= "`qd4_6a`, ";
			$sql .= "`qd5`, ";
			$sql .= "`qd6`, ";
			$sql .= "`qd6_6a`, ";
			$sql .= "`qd7`, ";
			$sql .= "`qd7_5a`, ";
			$sql .= "`qd8_1`, ";
			$sql .= "`qd8_2`, ";
			$sql .= "`qd8_3`, ";
			$sql .= "`qd8_4`, ";
			$sql .= "`qd8_5`, ";
			$sql .= "`qd8_6`, ";
			$sql .= "`qd9_1`, ";
			$sql .= "`qd9_2`, ";
			$sql .= "`qd9_3`, ";
			$sql .= "`qd9_4`, ";
			$sql .= "`qd9_5`, ";
			$sql .= "`qd9_6`, ";
			$sql .= "`qd10_1`, ";
			$sql .= "`qd10_2`, ";
			$sql .= "`qd10_3`, ";
			$sql .= "`qd10_4`, ";
			$sql .= "`qd10_5`, ";
			$sql .= "`qd10_6`, ";
			$sql .= "`qd11_1`, ";
			$sql .= "`qd11_2`, ";
			$sql .= "`qd11_3`, ";
			$sql .= "`qd11_4`, ";
			$sql .= "`qd11_5`, ";
			$sql .= "`qd11_6`, ";
			$sql .= "`qd12_1`, ";
			$sql .= "`qd12_2`, ";
			$sql .= "`qd12_3`, ";
			$sql .= "`qd12_4`, ";
			$sql .= "`qd12_5`, ";
			$sql .= "`qd12_6`, ";
			$sql .= "`qse1_1`, ";
			$sql .= "`qse1_2`, ";
			$sql .= "`qse1_3`, ";
			$sql .= "`qse1_4`, ";
			$sql .= "`qse1_5`, ";
			$sql .= "`qse1_6`, ";
			$sql .= "`qse2_1`, ";
			$sql .= "`qse2_2`, ";
			$sql .= "`qse2_3`, ";
			$sql .= "`qse2_4`, ";
			$sql .= "`qse2_5`, ";
			$sql .= "`qse2_6`, ";
			$sql .= "`qse3_1`, ";
			$sql .= "`qse3_2`, ";
			$sql .= "`qse3_3`, ";
			$sql .= "`qse3_4`, ";
			$sql .= "`qse3_5`, ";
			$sql .= "`qse3_6`, ";
			$sql .= "`qse4_1`, ";
			$sql .= "`qse4_2`, ";
			$sql .= "`qse4_3`, ";
			$sql .= "`qse4_4`, ";
			$sql .= "`qse4_5`, ";
			$sql .= "`qse4_6`, ";
			$sql .= "`qse5_1`, ";
			$sql .= "`qse5_2`, ";
			$sql .= "`qse5_3`, ";
			$sql .= "`qse5_4`, ";
			$sql .= "`qse5_5`, ";
			$sql .= "`qse5_6`, ";
			$sql .= "`qse6_1`, ";
			$sql .= "`qse6_2`, ";
			$sql .= "`qse6_3`, ";
			$sql .= "`qse6_4`, ";
			$sql .= "`qse6_5`, ";
			$sql .= "`qse6_6`, ";
			$sql .= "`qse7_1`, ";
			$sql .= "`qse7_2`, ";
			$sql .= "`qse7_3`, ";
			$sql .= "`qse7_4`, ";
			$sql .= "`qse7_5`, ";
			$sql .= "`qse7_6`, ";
			$sql .= "`qse8_1`, ";
			$sql .= "`qse8_2`, ";
			$sql .= "`qse8_3`, ";
			$sql .= "`qse8_4`, ";
			$sql .= "`qse8_5`, ";
			$sql .= "`qse8_6`, ";
			$sql .= "`qse9_1`, ";
			$sql .= "`qse9_2`, ";
			$sql .= "`qse9_3`, ";
			$sql .= "`qse9_4`, ";
			$sql .= "`qse9_5`, ";
			$sql .= "`qse9_6`, ";
			$sql .= "`qse10_1`, ";
			$sql .= "`qse10_2`, ";
			$sql .= "`qse10_3`, ";
			$sql .= "`qse10_4`, ";
			$sql .= "`qse10_5`, ";
			$sql .= "`qse10_6`, ";
			$sql .= "`qse11_1`, ";
			$sql .= "`qse11_2`, ";
			$sql .= "`qse11_3`, ";
			$sql .= "`qse11_4`, ";
			$sql .= "`qse11_5`, ";
			$sql .= "`qse11_6`, ";
			$sql .= "`qse12_1`, ";
			$sql .= "`qse12_2`, ";
			$sql .= "`qse12_3`, ";
			$sql .= "`qse12_4`, ";
			$sql .= "`qse12_5`, ";
			$sql .= "`qse12_6`, ";
			$sql .= "`qse13_1`, ";
			$sql .= "`qse13_2`, ";
			$sql .= "`qse13_3`, ";
			$sql .= "`qse13_4`, ";
			$sql .= "`qse13_5`, ";
			$sql .= "`qse13_6`, ";
			$sql .= "`qse14_1`, ";
			$sql .= "`qse14_2`, ";
			$sql .= "`qse14_3`, ";
			$sql .= "`qse14_4`, ";
			$sql .= "`qse14_5`, ";
			$sql .= "`qse14_6`, ";
			$sql .= "`qse15_1`, ";
			$sql .= "`qse15_2`, ";
			$sql .= "`qse15_3`, ";
			$sql .= "`qse15_4`, ";
			$sql .= "`qse15_5`, ";
			$sql .= "`qse15_6`, ";
			$sql .= "`qse16_1`, ";
			$sql .= "`qse16_2`, ";
			$sql .= "`qse16_3`, ";
			$sql .= "`qse16_4`, ";
			$sql .= "`qse16_5`, ";
			$sql .= "`qse16_6`, ";
			$sql .= "`qse17_1`, ";
			$sql .= "`qse17_2`, ";
			$sql .= "`qse17_3`, ";
			$sql .= "`qse17_4`, ";
			$sql .= "`qse17_5`, ";
			$sql .= "`qse17_6`, ";
			$sql .= "`qse18a`, ";
			$sql .= "`qse18b`, ";
			$sql .= "`qse18c`, ";
			$sql .= "`qa1_1a`, ";
			$sql .= "`qa2_1a`, ";
			$sql .= "`qa3_1a`, ";
			$sql .= "`qa4_1a`, ";
			$sql .= "`qpoc1`, ";
			$sql .= "`qpoc2`, ";
			$sql .= "`qpoc2_1a`, ";
			$sql .= "`qa5`, ";
			$sql .= "`qa6a`, ";
			$sql .= "`qa6b`, ";
			$sql .= "`qa6c`, ";
			$sql .= "`qa6d`, ";
			$sql .= "`qa6da`, ";
			$sql .= "`qa7`, ";
			$sql .= "`qa8a`, ";
			$sql .= "`qa8b` ";
			$sql .= ") values (";
			$sql .= "'".@$_POST["sc"]."',";
			$sql .= "'".@$_POST["mm"]."',";
			$sql .= "'".@$_POST["dd"]."',";
			$sql .= "'".@$_POST["yy"]."',";
			$sql .= "'".@$_POST["tt"]."',";
			$sql .= "'".@$_POST["eno"]."',";
			$sql .= "'".@$_POST["qx1"]."',";
			$sql .= "'".@$_POST["qx2"]."',";
			$sql .= "'".@$_POST["qx3"]."',";
			$sql .= "'".@$_POST["qb1"]."',";
			$sql .= "'".@$_POST["qb2_1"]."',";
			$sql .= "'".@$_POST["qb2_2"]."',";
			$sql .= "'".@$_POST["qb2_3"]."',";
			$sql .= "'".@$_POST["qb2_4"]."',";
			$sql .= "'".@$_POST["qb2_5"]."',";
			$sql .= "'".@$_POST["qb2_6"]."',";
			$sql .= "'".@$_POST["qb2_7"]."',";
			$sql .= "'".@$_POST["qb2_8"]."',";
			$sql .= "'".@$_POST["qb2_8a"]."',";
			$sql .= "'".@$_POST["qb3"]."',";
			$sql .= "'".@$_POST["qb3_1a"]."',";
			$sql .= "'".@$_POST["qb3_3a"]."',";
			$sql .= "'".@$_POST["qb3_4a"]."',";
			$sql .= "'".@$_POST["qb3a"]."',";
			$sql .= "'".@$_POST["qb3a_4a"]."',";
			$sql .= "'".@$_POST["qb3b"]."',";
			$sql .= "'".@$_POST["qb4"]."',";
			$sql .= "'".@$_POST["qb5"]."',";
			$sql .= "'".@$_POST["qb5_99a"]."',";
			$sql .= "'".@$_POST["qb6"]."',";
			$sql .= "'".@$_POST["qb6_5a"]."',";
			$sql .= "'".@$_POST["qb7"]."',";
			$sql .= "'".@$_POST["qb7_2a"]."',";
			$sql .= "'".@$_POST["qb7a_1a"]."',";
			$sql .= "'".@$_POST["qb7a_2a"]."',";
			$sql .= "'".@$_POST["qb7a_3a"]."',";
			$sql .= "'".@$_POST["qb7a_4a"]."',";
			$sql .= "'".@$_POST["qb7a_5a"]."',";
			$sql .= "'".@$_POST["qb7a_6b"]."',";
			$sql .= "'".@$_POST["qb7a_6a"]."',";
			$sql .= "'".@$_POST["qb8"]."',";
			$sql .= "'".@$_POST["qb9"]."',";
			$sql .= "'".@$_POST["qb10"]."',";
			$sql .= "'".@$_POST["qb11"]."',";
			$sql .= "'".@$_POST["qb12"]."',";
			$sql .= "'".@$_POST["qb12_4a"]."',";
			$sql .= "'".@$_POST["qb12_7a"]."',";
			$sql .= "'".@$_POST["qb13"]."',";
			$sql .= "'".@$_POST["qb13_9a"]."',";
			$sql .= "'".@$_POST["qb14"]."',";
			$sql .= "'".@$_POST["qg1"]."',";
			$sql .= "'".@$_POST["qg2"]."',";
			$sql .= "'".@$_POST["qg2a"]."',";
			$sql .= "'".@$_POST["qg2b"]."',";
			$sql .= "'".@$_POST["qg3"]."',";
			$sql .= "'".@$_POST["qg3a"]."',";
			$sql .= "'".@$_POST["qg4"]."',";
			$sql .= "'".@$_POST["qg4a_1"]."',";
			$sql .= "'".@$_POST["qg4a_2"]."',";
			$sql .= "'".@$_POST["qg4a_3"]."',";
			$sql .= "'".@$_POST["qg4a_4"]."',";
			$sql .= "'".@$_POST["qg4a_5"]."',";
			$sql .= "'".@$_POST["qg4a_6"]."',";
			$sql .= "'".@$_POST["qg4a_7"]."',";
			$sql .= "'".@$_POST["qg4a_8"]."',";
			$sql .= "'".@$_POST["qg4a_9"]."',";
			$sql .= "'".@$_POST["qg4a_10"]."',";
			$sql .= "'".@$_POST["qg4a_11"]."',";
			$sql .= "'".@$_POST["qg4a_11a"]."',";
			$sql .= "'".@$_POST["qhb1"]."',";
			$sql .= "'".@$_POST["qhb2"]."',";
			$sql .= "'".@$_POST["qhb3"]."',";
			$sql .= "'".@$_POST["qhb4"]."',";
			$sql .= "'".@$_POST["qhb13a_0"]."',";
			$sql .= "'".@$_POST["qhb13a_1"]."',";
			$sql .= "'".@$_POST["qhb13a_2"]."',";
			$sql .= "'".@$_POST["qhb13a_3"]."',";
			$sql .= "'".@$_POST["qhb13b_0"]."',";
			$sql .= "'".@$_POST["qhb13b_1"]."',";
			$sql .= "'".@$_POST["qhb13b_2"]."',";
			$sql .= "'".@$_POST["qhb13b_3"]."',";
			$sql .= "'".@$_POST["qhb13c_0"]."',";
			$sql .= "'".@$_POST["qhb13c_1"]."',";
			$sql .= "'".@$_POST["qhb13c_2"]."',";
			$sql .= "'".@$_POST["qhb13c_3"]."',";
			$sql .= "'".@$_POST["qhb13d_0"]."',";
			$sql .= "'".@$_POST["qhb13d_1"]."',";
			$sql .= "'".@$_POST["qhb13d_2"]."',";
			$sql .= "'".@$_POST["qhb13d_3"]."',";
			$sql .= "'".@$_POST["qhb13e_0"]."',";
			$sql .= "'".@$_POST["qhb13e_1"]."',";
			$sql .= "'".@$_POST["qhb13e_2"]."',";
			$sql .= "'".@$_POST["qhb13e_3"]."',";
			$sql .= "'".@$_POST["qhb13f_0"]."',";
			$sql .= "'".@$_POST["qhb13f_1"]."',";
			$sql .= "'".@$_POST["qhb13f_2"]."',";
			$sql .= "'".@$_POST["qhb13f_3"]."',";
			$sql .= "'".@$_POST["qhb13g_0"]."',";
			$sql .= "'".@$_POST["qhb13g_1"]."',";
			$sql .= "'".@$_POST["qhb13g_2"]."',";
			$sql .= "'".@$_POST["qhb13g_3"]."',";
			$sql .= "'".@$_POST["qhb13h_0"]."',";
			$sql .= "'".@$_POST["qhb13h_1"]."',";
			$sql .= "'".@$_POST["qhb13h_2"]."',";
			$sql .= "'".@$_POST["qhb13h_3"]."',";
			$sql .= "'".@$_POST["qhb13i_0"]."',";
			$sql .= "'".@$_POST["qhb13i_1"]."',";
			$sql .= "'".@$_POST["qhb13i_2"]."',";
			$sql .= "'".@$_POST["qhb13i_3"]."',";
			$sql .= "'".@$_POST["qhb13j_0"]."',";
			$sql .= "'".@$_POST["qhb13j_1"]."',";
			$sql .= "'".@$_POST["qhb13j_2"]."',";
			$sql .= "'".@$_POST["qhb13j_3"]."',";
			$sql .= "'".@$_POST["qhb13k_0"]."',";
			$sql .= "'".@$_POST["qhb13k_1"]."',";
			$sql .= "'".@$_POST["qhb13k_2"]."',";
			$sql .= "'".@$_POST["qhb13k_3"]."',";
			$sql .= "'".@$_POST["qmh4_1"]."',";
			$sql .= "'".@$_POST["qmh4_2"]."',";
			$sql .= "'".@$_POST["qmh4_3"]."',";
			$sql .= "'".@$_POST["qmh4_4"]."',";
			$sql .= "'".@$_POST["qmh4_5"]."',";
			$sql .= "'".@$_POST["qmh4_6"]."',";
			$sql .= "'".@$_POST["qmh4_7"]."',";
			$sql .= "'".@$_POST["qmh4_8"]."',";
			$sql .= "'".@$_POST["qmh4_9"]."',";
			$sql .= "'".@$_POST["qmh5a"]."',";
			$sql .= "'".@$_POST["qmh5b"]."',";
			$sql .= "'".@$_POST["qmh5b_5a"]."',";
			$sql .= "'".@$_POST["qmh5c_1"]."',";
			$sql .= "'".@$_POST["qmh5c_2"]."',";
			$sql .= "'".@$_POST["qmh5c_3"]."',";
			$sql .= "'".@$_POST["qmh5c_4"]."',";
			$sql .= "'".@$_POST["qmh5c_5"]."',";
			$sql .= "'".@$_POST["qmh5c_5a"]."',";
			$sql .= "'".@$_POST["qs1"]."',";
			$sql .= "'".@$_POST["qs1a"]."',";
			$sql .= "'".@$_POST["qs2"]."',";
			$sql .= "'".@$_POST["qs3"]."',";
			$sql .= "'".@$_POST["qs4"]."',";
			$sql .= "'".@$_POST["qs5"]."',";
			$sql .= "'".@$_POST["qs5a"]."',";
			$sql .= "'".@$_POST["qs6"]."',";
			$sql .= "'".@$_POST["qs8"]."',";
			$sql .= "'".@$_POST["qc1_1"]."',";
			$sql .= "'".@$_POST["qc1_1_8a"]."',";
			$sql .= "'".@$_POST["qc1_2"]."',";
			$sql .= "'".@$_POST["qc1_2_8a"]."',";
			$sql .= "'".@$_POST["qc2"]."',";
			$sql .= "'".@$_POST["qc3"]."',";
			$sql .= "'".@$_POST["qc4"]."',";
			$sql .= "'".@$_POST["qc5"]."',";
			$sql .= "'".@$_POST["qc6"]."',";
			$sql .= "'".@$_POST["qc7"]."',";
			$sql .= "'".@$_POST["qce1"]."',";
			$sql .= "'".@$_POST["qce2"]."',";
			$sql .= "'".@$_POST["qce3"]."',";
			$sql .= "'".@$_POST["qce4"]."',";
			$sql .= "'".@$_POST["qce5"]."',";
			$sql .= "'".@$_POST["qce6"]."',";
			$sql .= "'".@$_POST["qce7"]."',";
			$sql .= "'".@$_POST["qce8"]."',";
			$sql .= "'".@$_POST["qce9"]."',";
			$sql .= "'".@$_POST["qce10"]."',";
			$sql .= "'".@$_POST["qce11"]."',";
			$sql .= "'".@$_POST["qce12"]."',";
			$sql .= "'".@$_POST["qce13"]."',";
			$sql .= "'".@$_POST["qce14"]."',";
			$sql .= "'".@$_POST["qfs1"]."',";
			$sql .= "'".@$_POST["qfs2"]."',";
			$sql .= "'".@$_POST["qfs3"]."',";
			$sql .= "'".@$_POST["qfs4"]."',";
			$sql .= "'".@$_POST["qst2"]."',";
			$sql .= "'".@$_POST["qst2_4a"]."',";
			$sql .= "'".@$_POST["qst3"]."',";
			$sql .= "'".@$_POST["qst4"]."',";
			$sql .= "'".@$_POST["qst5"]."',";
			$sql .= "'".@$_POST["qst6"]."',";
			$sql .= "'".@$_POST["qst6_7a"]."',";
			$sql .= "'".@$_POST["qst7"]."',";
			$sql .= "'".@$_POST["qst7_7a"]."',";
			$sql .= "'".@$_POST["qst8"]."',";
			$sql .= "'".@$_POST["qst8_5a"]."',";
			$sql .= "'".@$_POST["qst9"]."',";
			$sql .= "'".@$_POST["qst10"]."',";
			$sql .= "'".@$_POST["qsa1"]."',";
			$sql .= "'".@$_POST["qsa2"]."',";
			$sql .= "'".@$_POST["qsa3"]."',";
			$sql .= "'".@$_POST["qsa4"]."',";
			$sql .= "'".@$_POST["qsa4_5a"]."',";
			$sql .= "'".@$_POST["qsa5"]."',";
			$sql .= "'".@$_POST["qd0"]."',";
			$sql .= "'".@$_POST["qd1"]."',";
			$sql .= "'".@$_POST["qd1_6a"]."',";
			$sql .= "'".@$_POST["qd2"]."',";
			$sql .= "'".@$_POST["qd3"]."',";
			$sql .= "'".@$_POST["qd3a"]."',";
			$sql .= "'".@$_POST["qd3aa"]."',";
			$sql .= "'".@$_POST["qd3b"]."',";
			$sql .= "'".@$_POST["qd3ba"]."',";
			$sql .= "'".@$_POST["qd3c"]."',";
			$sql .= "'".@$_POST["qd3ca"]."',";
			$sql .= "'".@$_POST["qd3d"]."',";
			$sql .= "'".@$_POST["qd3da"]."',";
			$sql .= "'".@$_POST["qd3e"]."',";
			$sql .= "'".@$_POST["qd3ea"]."',";
			$sql .= "'".@$_POST["qd3f"]."',";
			$sql .= "'".@$_POST["qd3fa"]."',";
			$sql .= "'".@$_POST["qd3g"]."',";
			$sql .= "'".@$_POST["qd3ga"]."',";
			$sql .= "'".@$_POST["qd3h"]."',";
			$sql .= "'".@$_POST["qd3ha"]."',";
			$sql .= "'".@$_POST["qd3i"]."',";
			$sql .= "'".@$_POST["qd3ia"]."',";
			$sql .= "'".@$_POST["qd3j"]."',";
			$sql .= "'".@$_POST["qd3ja"]."',";
			$sql .= "'".@$_POST["qd3k"]."',";
			$sql .= "'".@$_POST["qd3ka"]."',";
			$sql .= "'".@$_POST["qd3l"]."',";
			$sql .= "'".@$_POST["qd3la"]."',";
			$sql .= "'".@$_POST["qd3_12a"]."',";
			$sql .= "'".@$_POST["qd3m"]."',";
			$sql .= "'".@$_POST["qd4_1"]."',";
			$sql .= "'".@$_POST["qd4_2"]."',";
			$sql .= "'".@$_POST["qd4_3"]."',";
			$sql .= "'".@$_POST["qd4_4"]."',";
			$sql .= "'".@$_POST["qd4_5"]."',";
			$sql .= "'".@$_POST["qd4_6"]."',";
			$sql .= "'".@$_POST["qd4_6a"]."',";
			$sql .= "'".@$_POST["qd5"]."',";
			$sql .= "'".@$_POST["qd6"]."',";
			$sql .= "'".@$_POST["qd6_6a"]."',";
			$sql .= "'".@$_POST["qd7"]."',";
			$sql .= "'".@$_POST["qd7_5a"]."',";
			$sql .= "'".@$_POST["qd8_1"]."',";
			$sql .= "'".@$_POST["qd8_2"]."',";
			$sql .= "'".@$_POST["qd8_3"]."',";
			$sql .= "'".@$_POST["qd8_4"]."',";
			$sql .= "'".@$_POST["qd8_5"]."',";
			$sql .= "'".@$_POST["qd8_6"]."',";
			$sql .= "'".@$_POST["qd9_1"]."',";
			$sql .= "'".@$_POST["qd9_2"]."',";
			$sql .= "'".@$_POST["qd9_3"]."',";
			$sql .= "'".@$_POST["qd9_4"]."',";
			$sql .= "'".@$_POST["qd9_5"]."',";
			$sql .= "'".@$_POST["qd9_6"]."',";
			$sql .= "'".@$_POST["qd10_1"]."',";
			$sql .= "'".@$_POST["qd10_2"]."',";
			$sql .= "'".@$_POST["qd10_3"]."',";
			$sql .= "'".@$_POST["qd10_4"]."',";
			$sql .= "'".@$_POST["qd10_5"]."',";
			$sql .= "'".@$_POST["qd10_6"]."',";
			$sql .= "'".@$_POST["qd11_1"]."',";
			$sql .= "'".@$_POST["qd11_2"]."',";
			$sql .= "'".@$_POST["qd11_3"]."',";
			$sql .= "'".@$_POST["qd11_4"]."',";
			$sql .= "'".@$_POST["qd11_5"]."',";
			$sql .= "'".@$_POST["qd11_6"]."',";
			$sql .= "'".@$_POST["qd12_1"]."',";
			$sql .= "'".@$_POST["qd12_2"]."',";
			$sql .= "'".@$_POST["qd12_3"]."',";
			$sql .= "'".@$_POST["qd12_4"]."',";
			$sql .= "'".@$_POST["qd12_5"]."',";
			$sql .= "'".@$_POST["qd12_6"]."',";
			$sql .= "'".@$_POST["qse1_1"]."',";
			$sql .= "'".@$_POST["qse1_2"]."',";
			$sql .= "'".@$_POST["qse1_3"]."',";
			$sql .= "'".@$_POST["qse1_4"]."',";
			$sql .= "'".@$_POST["qse1_5"]."',";
			$sql .= "'".@$_POST["qse1_6"]."',";
			$sql .= "'".@$_POST["qse2_1"]."',";
			$sql .= "'".@$_POST["qse2_2"]."',";
			$sql .= "'".@$_POST["qse2_3"]."',";
			$sql .= "'".@$_POST["qse2_4"]."',";
			$sql .= "'".@$_POST["qse2_5"]."',";
			$sql .= "'".@$_POST["qse2_6"]."',";
			$sql .= "'".@$_POST["qse3_1"]."',";
			$sql .= "'".@$_POST["qse3_2"]."',";
			$sql .= "'".@$_POST["qse3_3"]."',";
			$sql .= "'".@$_POST["qse3_4"]."',";
			$sql .= "'".@$_POST["qse3_5"]."',";
			$sql .= "'".@$_POST["qse3_6"]."',";
			$sql .= "'".@$_POST["qse4_1"]."',";
			$sql .= "'".@$_POST["qse4_2"]."',";
			$sql .= "'".@$_POST["qse4_3"]."',";
			$sql .= "'".@$_POST["qse4_4"]."',";
			$sql .= "'".@$_POST["qse4_5"]."',";
			$sql .= "'".@$_POST["qse4_6"]."',";
			$sql .= "'".@$_POST["qse5_1"]."',";
			$sql .= "'".@$_POST["qse5_2"]."',";
			$sql .= "'".@$_POST["qse5_3"]."',";
			$sql .= "'".@$_POST["qse5_4"]."',";
			$sql .= "'".@$_POST["qse5_5"]."',";
			$sql .= "'".@$_POST["qse5_6"]."',";
			$sql .= "'".@$_POST["qse6_1"]."',";
			$sql .= "'".@$_POST["qse6_2"]."',";
			$sql .= "'".@$_POST["qse6_3"]."',";
			$sql .= "'".@$_POST["qse6_4"]."',";
			$sql .= "'".@$_POST["qse6_5"]."',";
			$sql .= "'".@$_POST["qse6_6"]."',";
			$sql .= "'".@$_POST["qse7_1"]."',";
			$sql .= "'".@$_POST["qse7_2"]."',";
			$sql .= "'".@$_POST["qse7_3"]."',";
			$sql .= "'".@$_POST["qse7_4"]."',";
			$sql .= "'".@$_POST["qse7_5"]."',";
			$sql .= "'".@$_POST["qse7_6"]."',";
			$sql .= "'".@$_POST["qse8_1"]."',";
			$sql .= "'".@$_POST["qse8_2"]."',";
			$sql .= "'".@$_POST["qse8_3"]."',";
			$sql .= "'".@$_POST["qse8_4"]."',";
			$sql .= "'".@$_POST["qse8_5"]."',";
			$sql .= "'".@$_POST["qse8_6"]."',";
			$sql .= "'".@$_POST["qse9_1"]."',";
			$sql .= "'".@$_POST["qse9_2"]."',";
			$sql .= "'".@$_POST["qse9_3"]."',";
			$sql .= "'".@$_POST["qse9_4"]."',";
			$sql .= "'".@$_POST["qse9_5"]."',";
			$sql .= "'".@$_POST["qse9_6"]."',";
			$sql .= "'".@$_POST["qse10_1"]."',";
			$sql .= "'".@$_POST["qse10_2"]."',";
			$sql .= "'".@$_POST["qse10_3"]."',";
			$sql .= "'".@$_POST["qse10_4"]."',";
			$sql .= "'".@$_POST["qse10_5"]."',";
			$sql .= "'".@$_POST["qse10_6"]."',";
			$sql .= "'".@$_POST["qse11_1"]."',";
			$sql .= "'".@$_POST["qse11_2"]."',";
			$sql .= "'".@$_POST["qse11_3"]."',";
			$sql .= "'".@$_POST["qse11_4"]."',";
			$sql .= "'".@$_POST["qse11_5"]."',";
			$sql .= "'".@$_POST["qse11_6"]."',";
			$sql .= "'".@$_POST["qse12_1"]."',";
			$sql .= "'".@$_POST["qse12_2"]."',";
			$sql .= "'".@$_POST["qse12_3"]."',";
			$sql .= "'".@$_POST["qse12_4"]."',";
			$sql .= "'".@$_POST["qse12_5"]."',";
			$sql .= "'".@$_POST["qse12_6"]."',";
			$sql .= "'".@$_POST["qse13_1"]."',";
			$sql .= "'".@$_POST["qse13_2"]."',";
			$sql .= "'".@$_POST["qse13_3"]."',";
			$sql .= "'".@$_POST["qse13_4"]."',";
			$sql .= "'".@$_POST["qse13_5"]."',";
			$sql .= "'".@$_POST["qse13_6"]."',";
			$sql .= "'".@$_POST["qse14_1"]."',";
			$sql .= "'".@$_POST["qse14_2"]."',";
			$sql .= "'".@$_POST["qse14_3"]."',";
			$sql .= "'".@$_POST["qse14_4"]."',";
			$sql .= "'".@$_POST["qse14_5"]."',";
			$sql .= "'".@$_POST["qse14_6"]."',";
			$sql .= "'".@$_POST["qse15_1"]."',";
			$sql .= "'".@$_POST["qse15_2"]."',";
			$sql .= "'".@$_POST["qse15_3"]."',";
			$sql .= "'".@$_POST["qse15_4"]."',";
			$sql .= "'".@$_POST["qse15_5"]."',";
			$sql .= "'".@$_POST["qse15_6"]."',";
			$sql .= "'".@$_POST["qse16_1"]."',";
			$sql .= "'".@$_POST["qse16_2"]."',";
			$sql .= "'".@$_POST["qse16_3"]."',";
			$sql .= "'".@$_POST["qse16_4"]."',";
			$sql .= "'".@$_POST["qse16_5"]."',";
			$sql .= "'".@$_POST["qse16_6"]."',";
			$sql .= "'".@$_POST["qse17_1"]."',";
			$sql .= "'".@$_POST["qse17_2"]."',";
			$sql .= "'".@$_POST["qse17_3"]."',";
			$sql .= "'".@$_POST["qse17_4"]."',";
			$sql .= "'".@$_POST["qse17_5"]."',";
			$sql .= "'".@$_POST["qse17_6"]."',";
			$sql .= "'".@$_POST["qse18a"]."',";
			$sql .= "'".@$_POST["qse18b"]."',";
			$sql .= "'".@$_POST["qse18c"]."',";
			$sql .= "'".@$_POST["qa1_1a"]."',";
			$sql .= "'".@$_POST["qa2_1a"]."',";
			$sql .= "'".@$_POST["qa3_1a"]."',";
			$sql .= "'".@$_POST["qa4_1a"]."',";
			$sql .= "'".@$_POST["qpoc1"]."',";
			$sql .= "'".@$_POST["qpoc2"]."',";
			$sql .= "'".@$_POST["qpoc2_1a"]."',";
			$sql .= "'".@$_POST["qa5"]."',";
			$sql .= "'".@$_POST["qa6a"]."',";
			$sql .= "'".@$_POST["qa6b"]."',";
			$sql .= "'".@$_POST["qa6c"]."',";
			$sql .= "'".@$_POST["qa6d"]."',";
			$sql .= "'".@$_POST["qa6da"]."',";
			$sql .= "'".@$_POST["qa7"]."',";
			$sql .= "'".@$_POST["qa8a"]."',";
			$sql .= "'".@$_POST["qa8b"]."' ";
			$sql .= ");";
		}
		//echo $sql;
		$result = mysql_query($sql,$link);	
	}
//echo $sql;

	
	
	
	
	
	
	
	
	
	
/*	
	if (($sc != "x")&&($sc != "xx")) {
		$sql = "select * from icacbranddb where sc = '".$sc."'";
		$result = mysql_query($sql,$link);
		$num_rows = mysql_num_rows($result);
		if ($num_rows > 0) {
			$ans = mysql_fetch_assoc($result);
		}
	}
*/
@mysql_free_result($result);	
mysql_close($link);
?>